### ISSUE TITLE
[1.18.2] [Mod Incompatibility?] Crash on Launch

### ISSUE THREAD

**Issue by ConqAra** [Siphalor/bouncylife#14]
Crashes on launch with my modpack. Probably some weird mod incompatibility? 

[CrashLog](https://paste.ee/p/AfjlA)

**Comment by Siphalor** [comment]
Actually not an incompatibility but a bug with the mod itself, apparently the custom slime blocks related stuff is broken in newer Minecraft versions.
Interestingly enough it only occurs in the development environment when actually triggering a piston, launching the game is fine.

Should be easy to fix, but I don't have time for it right now - so I'll see tomorrow or during the next few days.
