### ISSUE TITLE
Dedicated server crash (Multithreading issue)

### ISSUE THREAD

**Issue by EvieTheOwl** [Siphalor/bouncylife#7]
Issue with the latest beta of bouncy life when trying to load onto a dedicated server for the first time
**Crash link**: https://gist.github.com/profjb58/691b9c7954694ec8085cc6757b8eb6c6

**Comment by Siphalor** [comment]
Fixed in Beta 3 of Version 1.2.0.
For the record: This was a bug in Push to Craft
